elk code
therahulsahu/product-spring-app pull request #9
Opened 2022-07-20 06:22 UTC by sundarmachani

2022-07-20 17:54 UTC, therahulsahu commented on product-service/src/main/java/com/product/service/ProductServiceImpl.java
> +			log.info("Getting product {}",new ObjectMapper().writeValueAsString(products));
instead of creating a new ObjectMapper object everytime while logging, create one as a private class field and use that variable instead.

2022-07-20 17:55 UTC, therahulsahu requested changes
address the comments.

2022-07-21 06:06 UTC, therahulsahu approved these changes

2022-07-21 06:08 UTC, Harshith1234567 approved these changes

2022-07-21 06:09 UTC, merged